from pathlib import Path
p=Path("/app/app/templates/connect/profile.html")
s=p.read_text(encoding="utf-8")
s=s.replace('<span class="xp-eyebrow">EXPONENTA CONNECT</span>','')
s=s.replace('<small>Conoce más del negocio</small>','<small>Síguenos y conoce más</small>')
s=s.replace('<small>Agrega el negocio a tu celular</small>','<small>Agrega a tu celular</small>')
s=s.replace('<footer class="xp-foot">Conectado por <b>Exponenta</b></footer>','<footer class="xp-foot">Powered by <b>Exponenta</b></footer>')
s=s.replace('<footer class="xp-foot">Powered by <b>Exponenta</b></footer>','<footer class="xp-foot">Powered by <a href="https://app.exponenta.mx" target="_blank" rel="noopener noreferrer" style="color:inherit;font-weight:700;text-decoration:underline;text-underline-offset:3px">Exponenta</a></footer>')
p.write_text(s,encoding="utf-8")
print("Public Connect labels updated")
